### ISSUE TITLE
Request - Cocoapod support

### ISSUE THREAD

**Issue by dariopellegrini** [belozierov/SwiftCoroutine#16]
Hi!
Wonderful and interesting project!
I was wondering if you're planning to support Cocoapod in future release.

Thank you!

**Comment by belozierov** [comment]
@dariopellegrini Hi, I’ve been thinking about CocoaPods and Carthage support. 

But starting from Xcode 11 Swift Package Manager became a really good alternative. You can always combine SPM and CocoaPods. So I don’t see a particular need to add CocoaPods support. 

If you could justify why you need CocoaPods and SPM doesn’t work for you, then I might add it.

**Comment by dariopellegrini** [comment]
Yes of course.
SwiftCoroutine is a generic and versatile library that can be used by other libraries (such as RxSwift or PromiseKit).
With Cocoapods developers can use and deliver SwiftCoroutine as a dependency of their pod (using Podspec file), especially when those pods contain some asynchronous code.

**Comment by belozierov** [comment]
@dariopellegrini  If I get you right, you want to use `SwiftCoroutine` as a dependency to other libraries that are distributed with `CocoaPods`, right?

P.S. Just want to highlight that you can use [Swift Package Manager](https://www.ralfebert.de/ios/swift-package-manager-for-ios-projects/) to deliver `SwiftCoroutine` as a dependency.

**Comment by dariopellegrini** [comment]
Yes but it is only an example use case. No problem using SPM of course. Compatibility with something so popular like Cocoapod could be useful to many for many reasons, as well giving library more visibility. More than saying “why I should add it” I would say “why I shouldn’t “.
Just a free opinion by the way.

**Comment by belozierov** [comment]
@dariopellegrini Yes, I think you totally right :) I will add it in the upcoming releases. Thanks for reaching out.

**Comment by belozierov** [comment]
@dariopellegrini Added)
