### ISSUE TITLE
Thread safety of CoChannels

### ISSUE THREAD

**Issue by wsb9** [belozierov/SwiftCoroutine#19]
Can `CoChannel` be cancelled from different thread than where it has been created? Ie, I create channels on `DispatchQueue.global()`, and cancel them later at `DispatchQueue.main`, as they become unneeded. But channels seem to continue working until app termination.

**Comment by belozierov** [comment]
@wsb9 Yes, of course, all api in library is thread safe. Сould you provide more info so I could reproduce it. Thx.

**Comment by wsb9** [comment]
Actually was caused by unrelated issue, I'm sorry.
