### ISSUE TITLE
Not able to build SwiftCoroutine for previews in xcode

### ISSUE THREAD

**Issue by singlakarun** [belozierov/SwiftCoroutine#21]
Getting this error when building/resuming my project for previews with SwiftCoroutine whereas normal build is successful.

in file CoPromise.swift, line: 19
extension CoPromise {
    @inlinable public convenience init() {
        self.init(_result: nil) --> **Initializer 'init(_result:)' is internal and cannot be referenced from an '@inlinable' function**
    }

**Comment by belozierov** [comment]
@singlakarun Thank you a lot!
