### ISSUE TITLE
How to await all futures in a collection?

### ISSUE THREAD

**Issue by heshuimu** [belozierov/SwiftCoroutine#23]
In Kotlin and C#, there are ways to await several coroutines in a collection at the same time, namely `Collection<Deferred<T>>.awaitAll()` and `Task.WhenAll(IEnumerable<Task>)` respectively. I now have a list of several `CoFuture<Void>` in an array (the amount of futures is dynamic) that I want to await at the same time instead of individually. Can I do this with current API?

**Comment by belozierov** [comment]
@heshuimu Hi, there is no such api but you can add it by yourself: 

```swift
extension Sequence where Element: CoFuture<Void> {
	
   func awaitAll() throws {
      try forEach { try $0.await() }
   }
	
}

extension Sequence {
	
   func awaitAll<T>() throws -> [T] where Element: CoFuture<T> {
      try map { try $0.await() }
   }
	
}
```

**Comment by heshuimu** [comment]
@belozierov I see. I forgot that I can `forEach`. I'll give it a try. Thanks so much!
