### ISSUE TITLE
ReactiveKit Bindings/Extensions for Migration

### ISSUE THREAD

**Issue by marcoRS** [belozierov/SwiftCoroutine#24]
Do you have any plans to include or create ReactiveKit type Bindings/Extensions for those of us who want to migrate a ReactiveKit style project to Coroutines? 

So something like:  `mySignal.await()` to be able to call within a coroutine function.

**Comment by belozierov** [comment]
@marcoRS Hi, I don't plan to make any extensions for integration with other libraries but you can do it by yourself. I'm not familiar with ReactiveKit but you can do something like this:

```swift
struct SignalCompleteError: Error {}

extension Signal {
	
   func await() throws -> Element {
      var observer: Disposable?
      return try Coroutine.await { (callback: @escaping (Result<Element, Swift.Error>) -> Void) in
         observer = observe { result in
            switch result {
            case .next(let element):
               callback(.success(element))
            case .failed(let error):
               callback(.failure(error))
            case .completed:
               callback(.failure(SignalCompleteError()))
            }
            observer?.dispose()
         }
      }.get()
   }
	
}
```
