### ISSUE TITLE
Recommended way to handle callbacks that return Swift.Result

### ISSUE THREAD

**Issue by balavigneshsureshkumar** [belozierov/SwiftCoroutine#26]
I'm not sure if this is where I should bring this up but it'll do for now, I guess. Anyway, is there a recommended way to handle callbacks that return enums like Swift.Result?

**Comment by belozierov** [comment]
@SomeRandomGuyOnTheInternet Hi, could you clarify with an example what you mean so I know exactly what case you're about.
