### ISSUE TITLE
Xcode 13 error compilation

### ISSUE THREAD

**Issue by emoonadev** [belozierov/SwiftCoroutine#39]
Hi,

The word await make a compilation error because apple have deployed his concurrency async await.

Can you fix this issues simple refactored methods name `func await()` to 
```func `await`()```
<img width="1095" alt="Capture d’écran 2021-09-23 à 17 45 13" src="https://user-images.githubusercontent.com/35075841/134529835-50bb290f-8edc-4647-b80f-1872a1eef344.png">

**Comment by ladeiko** [comment]
Fix is already in repo

**Comment by fpellicano** [comment]
> Fix is already in repo

Installing through Cocoapods using `pod 'SwiftCoroutine', '~> 2.1'` installs version 2.1.8 and not the latest version. What is the recommended way to install the latest version?

**Comment by ladeiko** [comment]
Just use commit not version

**Comment by niquetrevisan** [comment]
@ladeiko Can you show the commit code? I didn't find here.

**Comment by belozierov** [comment]
CocoaPods are out of date (there is a problem with updating it). Please use SPM if possible. 😒

**Comment by ishrek** [comment]
I got the same issue

Xcode 13
Cocoapods 1.11.2
Coroutine 2.1.8
Please support me :D

**Comment by belozierov** [comment]
CocoaPods version updated to 2.1.11 🙂
