### ISSUE TITLE
CoFutureAwaitTests.swift:51 - testConcurrency() - unit test fails

### ISSUE THREAD

**Issue by ctreffs** [belozierov/SwiftCoroutine#6]
When running the unit tests of the current master branch I get the following test crash 

```sh
commit 014ebe763cb08bb9e04dcf112787e585f7dc00f5 (HEAD -> master, origin/master, origin/HEAD)
```

In file and line: `CoFutureAwaitTests.swift:51`

![Bildschirmfoto 2020-03-30 um 09 21 21](https://user-images.githubusercontent.com/1262900/77885752-e48f0e80-7267-11ea-82c8-fadc3f29edc6.png)

```sh
xctest(7034,0x700009087000) malloc: *** error for object 0x111abe000: pointer being freed was not allocated
xctest(7034,0x700009087000) malloc: *** set a breakpoint in malloc_error_break to debug
```

- Xcode Version 11.4 (11E146)
- macOS Catalina 10.15.4 (19E266)
- MacBook Pro (16", 2019)

If it's of interest to you I will debug further using your instructions.

**Comment by belozierov** [comment]
@ctreffs Thanks a lot!!! I've always run tests in a release mode and didn't see that
crash in a debug mode. Thanks to this issue, I've found another bug too. Updated
version is on github.

**Comment by ctreffs** [comment]
![Bildschirmfoto 2020-03-30 um 10 07 12](https://user-images.githubusercontent.com/1262900/77889529-45214a00-726e-11ea-88b1-d4c72363ae74.png)

Works fine now ✅  `commit 6d4cda2ebe04fa5103d8892d81fa2339f009e74d (HEAD -> master, tag: 2.0.6, origin/master, origin/HEAD)
`
